# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-27 23:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data_crs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crs_type', models.CharField(default='name', max_length=4)),
                ('crs_properties_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='data_geo',
            fields=[
                ('geo_data_label', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('geo_data_type', models.CharField(default='FeatureCollection', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='feature_geometry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry_id', models.CharField(max_length=50)),
                ('geometry_type', models.CharField(default='Point', max_length=10)),
                ('coordinate_x', models.FloatField()),
                ('coordinate_y', models.FloatField()),
                ('coordinate_z', models.FloatField()),
                ('geometry_name', models.CharField(default='geom', max_length=4)),
                ('central_as', models.IntegerField()),
                ('site_name', models.CharField(max_length=200)),
                ('feature_lo', models.CharField(max_length=200)),
                ('feature_ty', models.CharField(max_length=200)),
                ('centroid_e', models.FloatField()),
                ('centroid_n', models.FloatField()),
                ('feature_data_crs', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='big_geo_ballarat.data_crs')),
                ('feature_data_geo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='big_geo_ballarat.data_geo')),
            ],
        ),
    ]
