# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-28 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('big_geo_ballarat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_geo',
            name='geo_data_table',
            field=models.CharField(default='Enter Table Reference Here', max_length=100),
        ),
    ]
