# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-25 23:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0004_auto_20161225_2251'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe_Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_me_link', models.CharField(max_length=100)),
                ('about_me_icon', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Reference_LinkIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LinkType', models.CharField(max_length=50)),
                ('IconTagText', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='aboutme',
            name='about_me_email',
        ),
        migrations.RemoveField(
            model_name='aboutme',
            name='about_me_github',
        ),
        migrations.RemoveField(
            model_name='aboutme',
            name='about_me_linkedin',
        ),
        migrations.AddField(
            model_name='aboutme_links',
            name='about_me_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myprofile.AboutMe'),
        ),
    ]
