# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-26 00:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0005_auto_20161225_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme_links',
            name='about_me_icon',
            field=models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, to='myprofile.Reference_LinkIcon'),
        ),
    ]
