# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-26 00:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0006_auto_20161226_0023'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AboutMe_Links',
            new_name='AboutMe_Link',
        ),
    ]
